#!/bin/bash

targets="x86_64-linux-android aarch64-linux-android x86_64-apple-ios aarch64-apple-ios"
commands="clang ld ld.gold nm ar ranlib cabal llvm-dis llvm-nm llvm-ar"

for target in $targets; do
	for command in $commands; do
		ln -s wrapper $target-$command
	done

	# create libtool wrapper for non apple platforms
	case "$target" in
		*-apple-*) continue;;
		*) ln -s libtool-lite $target-libtool;;
	esac
done
